# Docker


trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'CICDTerraForm'
        repository: 'vishaldocker59/weatherapi'
        command: 'buildAndPush'        
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)

      
  
    
  


